version: "3.7"
services:

## APCUPSD
  apcupsd:
    container_name: apcupsd
    image: gersilex/apcupsd
    restart: always
    networks:
      - traefik_proxy
    ports:
      - "3551:3551"
    privileged: true
    tty: true
    volumes:
      - /tmp/apcupsd-docker:/tmp/apcupsd-docker
      - ${USERDIR}/docker/apcupsd/apcupsd.conf:/etc/apcupsd/apcupsd.conf
      - ${USERDIR}/docker/apcupsd/doshutdown:/etc/apcupsd/doshutdown
      - ${USERDIR}/docker/apcupsd/apcupsd.events/var/log/apcupsd.events
      - ${USERDIR}/docker/shared:/shared

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

