version: "3.7"
services:

## Autoheal - Restart Unhealthy Containers
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=60   # Default checks every 5 seconds
      - AUTOHEAL_START_PERIOD=0   # wait 0 second before first health check

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
