version: "3.7"
services:

## Laverna - Web Notes
  # No support for iOS
  # Available at laverna.${DOMAINNAME}/laverna
  laverna:
    container_name: laverna
    image: thklein/laverna
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
    volumes:
      - ${USERDIR}/docker/shared:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.backend=laverna"
      - "traefik.frontend.rule=Host:laverna.${DOMAINNAME}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=laverna.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
