version: "3.7"
services:

## LeaNote - Note App
    # https://github.com/axboy/docker-leanote/blob/master/README-EN.md
  ## To Install:
    # Start LeaNote and MongoDB Containers
    # Edit app.conf file in config folder:
      # sudo nano ${USERDIR}/docker/leanote/config/app.conf
      # Change the following:
        # site.url (https://leanote.${DOMAINNAME})
        # db.host=mongo
        # also change some of the values in the "app.secret", but keep the length the same
    # Import LeaNote data to MongoDB:
      # docker exec -it leanote  mongorestore -h mongo -d leanote --dir /data/leanote/mongodb_backup/leanote_install_data
  leanote:
    container_name: leanote
    image: axboy/leanote
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "9000:9000"
    volumes:
      - ${USERDIR}/docker/leanote/config/:/data/leanote/conf
      - ${USERDIR}/docker/leanote/files:/data/leanote/files
      - ${USERDIR}/docker/leanote/upload:/data/leanote/public/upload
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.backend=leanote"
      - "traefik.frontend.rule=Host:leanote.${DOMAINNAME}"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=leanote.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
