version: "3.7"
services:

## Ouroboros
  # https://hub.docker.com/r/pyouroboros/ouroboros/
  # https://github.com/pyouroboros/ouroboros/wiki
  ouroboros:
    hostname: ouroboros
    container_name: ouroboros
    image: pyouroboros/ouroboros
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=${TZ}

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
