version: "3.7"
services:

## Samba - File sharing
  # Samba share IP is the IP of the server
  samba:
    container_name: samba
    image: dperson/samba
    restart: always
    command: >
      -s "share;/share;yes;no;yes"
    networks:
      - traefik_proxy
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /location/to/share:/share
#      - ${USERDIR}/docker/samba:/etc/samba
    environment:
      - TZ=${TZ}
      - USERID=1000
      - GROUPID=1000
      - NMBD=True
      - SMB=True
      - RECYCLE=True
#      - USER=user;pass
#      - WORKGROUP=

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
